apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  storageClassName: ""
  capacity:
    storage: 50G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: test-disk
---
