apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-nfs-pv
spec:
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.2
    path: /home/nfs-workernode01
  storageClassName: ""