apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  storageClassName: ""
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: disk-test